ClassLength:
  Enabled: false

CollectionMethods:
  Enabled: true

CyclomaticComplexity:
  Enabled: false

DefWithParentheses:
  Enabled: true

Documentation:
  Enabled: false

Eval:
  Enabled: true

FormatString:
  Enabled: true

HashSyntax:
  Enabled: true

LineLength:
  Enabled: true
  Max: 323

MethodLength:
  Enabled: true
  Max: 50

# TEMP ENABLED
AccessorMethodName:
  Enabled: false

AndOr:
  Enabled: true

Alias:
  Enabled: false

BracesAroundHashParameters:
  Enabled: true

CaseIndentation:
  Enabled: true

DeprecatedHashMethods:
  Enabled: true

EmptyLines:
  Enabled: true

EmptyLinesAroundBody:
  Enabled: true

EndAlignment:
  Enabled: true

Encoding:
  Enabled: true

FinalNewline:
  Enabled: true

GlobalVars:
  Enabled: false

IfUnlessModifier:
  Enabled: true

IndentationConsistency:
  Enabled: true

IndentationWidth:
  Enabled: true

IndentHash:
  Enabled: true

LeadingCommentSpace:
  Enabled: true

MethodCallParentheses:
  Enabled: true

MethodDefParentheses:
  Enabled: true

NegatedIf:
  Enabled: true

NonNilCheck:
  Enabled: true

OpMethod:
  Enabled: true

ParenthesesAroundCondition:
  Enabled: true

ParenthesesAsGroupedExpression:
  Enabled: true

RaiseArgs:
  Enabled: true

SpaceAfterComma:
  Enabled: true

SpaceAfterControlKeyword:
  Enabled: true

SpaceBeforeBlockBraces:
  Enabled: true

SpaceInsideBlockBraces:
  Enabled: true

SpaceInsideHashLiteralBraces:
  Enabled: true

SpaceInsideParens:
  Enabled: true

SignalException:
  Enabled: true

StringLiterals:
  Enabled: true

StringConversionInInterpolation:
  Enabled: true

TrivialAccessors:
  Enabled: true

UselessAssignment:
  Enabled: true
